version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  reviewers:
  - github-actions
  ignore:
  - dependency-name: webpack
    versions:
    - 5.21.0
    - 5.21.1
    - 5.31.1
    - 5.34.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.0.0
    - 8.1.0
